# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 055f38c762db489f190158f35b48a946fcd8f98b480480e7cc8f1d2e60a98b85ce51a7d5b64ef2c3b267c0fbf51969528ba5f0019bb5a958de71a796c1848f26

test:
  secret_key_base: 117a66b472aab1a63f8a6903026713c98ff61e9a7348f7cd8401973cb8c917b8410cd400d16361178ae85b3b567797b90764993b5e23082428e36cd4e7f7d617

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
